version: '3.7'
services:
  mongo:
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./db:/data/db
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=${MONGODB_ENABLE_ADMIN}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    links:
      - mongo
  api:
    build: ./backend
    working_dir: "/app"
    expose:
      - ${API_PORT}
    environment:
      API_PORT: ${API_PORT}
      MONGO_DB_CONNECTION_URI: ${MONGO_DB_CONNECTION_URI}
      APP_NAME: ${APP_NAME}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    links:
      - mongo
    command: sh -exec "npm install && npm run dev"

volumes:
  db: