import swaggerGen from 'swagger-autogen'
const swaggerAutogen = swaggerGen();
const outputFile = './swagger_output.json';
const endpointsFiles = ['./src/routes/endPoints.js'];

const doc = {
    info: {
        version: "1.0.0",
        title: "Hotel Offer API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Hotel Offers",
            "description": "Search by Hotel Offers"
        }
    ],
    definitions: {
        HotelOffers: {
            type: 'hotel-offers',
            hotel: {
                "$ref": "#/definitions/Hotel"
            },
            offers: {
                "type": "array",
            }
        },
        Hotel: {
            "description": {
                "lang": "BR",
                "text": "Um grande hotel"
            },
            "address": {
                "cityName": "City C1",
                "countryCode": "BR"
            },
            "type": "hotel",
            "hotelId": "HOTELID1",
            "name": "AWESOME HOTEL BR",
            "rating": "1",
            "location": {
                "coordinates": [
                    -168,
                    54
                ],
                "_id": "610752667bf71202c5280a13",
                "type": "Point"
            },
            "id": "610752667bf71202c5280a12"
        },
        HotelOffer: {
            "price": {
                "currency": "USD",
                "total": 129.99,
                "base": 120
            },
            "type": "hotel-offer",
            "checkInDate": "2021-08-02T00:00:00.000Z",
            "checkOutDate": "2021-08-03T00:00:00.000Z",
            "roomQuantity": 1,
            "createdAt": "2021-08-02T02:55:57.991Z",
            "updatedAt": "2021-08-02T02:55:57.991Z",
            "id": "61075ebdf6e0b006af08d261"
        }

    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then()


    